// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUNaw8yLnZGmB7tcnJzaCzxlwZSBSd9qA',
    appId: '1:274585145615:android:21c45f770da8304bc22e7a',
    messagingSenderId: '274585145615',
    projectId: 'maps-db2b6',
    storageBucket: 'maps-db2b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC49nNlPy6Vy9wzHqpsFye36z6ngLbTlVk',
    appId: '1:274585145615:ios:e845cef81159a839c22e7a',
    messagingSenderId: '274585145615',
    projectId: 'maps-db2b6',
    storageBucket: 'maps-db2b6.firebasestorage.app',
    iosBundleId: 'com.example.mapTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC49nNlPy6Vy9wzHqpsFye36z6ngLbTlVk',
    appId: '1:274585145615:ios:e845cef81159a839c22e7a',
    messagingSenderId: '274585145615',
    projectId: 'maps-db2b6',
    storageBucket: 'maps-db2b6.firebasestorage.app',
    iosBundleId: 'com.example.mapTask',
  );
}
